cmake_minimum_required(VERSION 3.16)
project(face_qt LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_AUTOMOC ON)
find_package(Qt6 COMPONENTS Widgets REQUIRED)
find_package(OpenCV REQUIRED)
add_executable(face_qt mainwindow.cpp FaceWorker.h)
target_include_directories(face_qt PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(face_qt PRIVATE Qt6::Widgets ${OpenCV_LIBS})
