import React from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, Download, Mail, MapPin, Menu, X, GitBranch, ExternalLink, FileCode2 } from 'lucide-react';
const Github = GitBranch;
import avatar from '../头像.png';
import '../styles.css';

const githubProfile = 'https://github.com/liw200507038051';
const projects = [
  { number: '01', title: '高性能 HTTP 服务器', english: 'HTTP SERVER', type: 'C++ / Linux / epoll', text: '基于非阻塞 IO、多路复用和线程池的 HTTP/1.1 静态资源服务器。', detail: '采用 Reactor 思路：主线程使用 epoll 监听连接，非阻塞 socket 读取请求，线程池处理解析和静态文件响应，并对路径穿越、半包和错误状态码做防护。', github: `${githubProfile}/HTTP-Server`, files: [['http_server.cpp', './project-code/http_server/http_server.cpp'], ['CMakeLists.txt', './project-code/http_server/CMakeLists.txt']], accent: 'lime' },
  { number: '02', title: 'STM32 两轮平衡小车', english: 'BALANCE CAR', type: 'STM32 / PID / Firmware', text: '姿态融合、编码器测速、串级 PID 与双轮 PWM 控制。', detail: '以固定周期执行姿态更新、编码器测速和串级 PID：姿态环负责快速平衡，速度环负责前后运动，转向量通过左右轮差速叠加输出。', github: `${githubProfile}/Bluetooth-Remote-Controlled-Car-System`, files: [['control.cpp', './project-code/balance_car/control.cpp'], ['pid.h', './project-code/balance_car/pid.h']], accent: 'blue' },
  { number: '03', title: 'Qt + OpenCV 人脸识别', english: 'FACE RECOGNITION', type: 'Qt / OpenCV / MySQL', text: '多线程视频处理、人脸检测识别与用户数据管理系统。', detail: 'UI 线程负责交互和显示，摄像头采集与 OpenCV 检测放在 worker 线程，通过 Qt 信号槽传回结果；MySQL 保存用户信息和特征文件索引。', github: `${githubProfile}/Qt-based-Face-Recognition`, files: [['FaceWorker.h', './project-code/face_qt/FaceWorker.h'], ['mainwindow.cpp', './project-code/face_qt/mainwindow.cpp'], ['schema.sql', './project-code/face_qt/schema.sql']], accent: 'orange' },
  { number: '04', title: 'STM32 智能风扇', english: 'SMART FAN', type: 'STM32 / HAL / PWM', text: '温湿度采集、红外遥控、自动/手动模式与 OLED 显示。', detail: '通过 DHT11、人体红外和红外遥控输入实现自动/手动状态机，使用 PWM 控制电机档位，OLED 显示温度、风速和工作模式。', github: `${githubProfile}/Intelligent-Fan-System`, files: [['fan_control.c', './project-code/smart_fan/fan_control.c']], accent: 'purple' },
];

function App() {
  const [menuOpen, setMenuOpen] = React.useState(false);
  const [selectedProject, setSelectedProject] = React.useState(null);
  const closeMenu = () => setMenuOpen(false);
  return <div className="app">
    <div className="ambient" aria-hidden="true" />
    <header className="nav"><a className="logo" href="#top">LI<span>.</span></a><nav className={menuOpen ? 'open' : ''}><a href="#about" onClick={closeMenu}>关于我</a><a href="#projects" onClick={closeMenu}>项目矩阵</a><a href="#contact" onClick={closeMenu}>联系</a></nav><a className="nav-cta" href={githubProfile} target="_blank" rel="noreferrer"><Github size={15} /> GitHub <ArrowUpRight size={14} /></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="打开导航">{menuOpen ? <X /> : <Menu />}</button></header>
    <main id="top">
      <section className="intro-wrap section" id="about"><div className="intro-card"><div className="intro-topline"><span className="status-dot" /> OPEN TO OPPORTUNITIES <span className="intro-index">00 / PROFILE</span></div><div className="intro-main"><div className="intro-copy"><p className="eyebrow">ELECTRONICS ENGINEERING · CHANGSHA</p><h1>你好，我是<br /><em>李旺。</em></h1><p className="intro-lede">电子信息工程本科生，专注嵌入式开发与 C/C++ 系统实践。喜欢从底层理解系统，再把复杂的想法做成可靠、可运行的作品。</p><div className="intro-actions"><a className="solid-btn" href="#projects">浏览项目 <ArrowUpRight size={16} /></a><a className="outline-btn" href="./简历.pdf" download="李旺-简历.pdf"><Download size={15} /> 下载简历</a></div></div><div className="intro-portrait"><div className="portrait-ring"><img src={avatar} alt="李旺的头像" /></div><span>LI WANG / 2026</span></div></div><div className="intro-bottom"><div className="contact-chips"><a href="mailto:nameliwang1@outlook.com"><Mail size={15} /> nameliwang1@outlook.com</a><span><MapPin size={15} /> 湖南 · 长沙</span><a href={githubProfile} target="_blank" rel="noreferrer"><Github size={15} /> liw200507038051</a></div><div className="quick-stats"><span><strong>17%</strong>专业排名</span><span><strong>03+</strong>实践项目</span><span><strong>C/C++</strong>核心语言</span></div></div></div></section>
      <section className="projects section" id="projects"><div className="section-heading"><div><p className="eyebrow"><i /> SELECTED WORK</p><h2>项目矩阵<span> / 04</span></h2></div><p className="section-description">来自简历与 GitHub 的实践项目<br />每一格都连接到工程代码。</p></div><div className="project-list">{projects.map((project) => <article className={`project-card ${project.accent}`} key={project.number}><div className="project-visual"><span className="project-number">{project.number}</span><span className="project-english">{project.english}</span><div className="visual-mark">{project.number}</div><span className="visual-line" /></div><div className="project-info"><span className="project-type">{project.type}</span><h3>{project.title}</h3><p>{project.text}</p><div className="project-actions"><button className="detail-btn" onClick={() => setSelectedProject(project)}>项目介绍 <ArrowUpRight size={15} /></button><a className="github-btn" href={project.github} target="_blank" rel="noreferrer"><Github size={14} /> GitHub</a></div><div className="project-files">{project.files.map(([name, href]) => <a href={href} download key={href}><FileCode2 size={14} /> {name} <Download size={12} /></a>)}</div></div></article>)}</div><div className="projects-footer"><span>更多实验与学习记录持续更新中</span><a href={githubProfile} target="_blank" rel="noreferrer">查看全部 GitHub 仓库 <ArrowUpRight size={14} /></a></div></section>
      <section className="contact section" id="contact"><div className="contact-inner"><p className="eyebrow"><i /> 03 / GET IN TOUCH</p><h2>一起做点<br /><em>有意思的事。</em></h2><div className="contact-bottom"><a className="solid-btn" href="mailto:nameliwang1@outlook.com">发一封邮件 <ArrowUpRight size={16} /></a><div><a href="mailto:nameliwang1@outlook.com">nameliwang1@outlook.com</a><a href="tel:17670610270">176 7061 0270</a><span>长沙 · 中国</span></div></div></div></section>
    </main>
    {selectedProject && <div className="modal-backdrop" role="presentation" onClick={() => setSelectedProject(null)}><section className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-dialog-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelectedProject(null)} aria-label="关闭项目介绍"><X size={20} /></button><span className="project-type">{selectedProject.number} / {selectedProject.type}</span><h2 id="project-dialog-title">{selectedProject.title}</h2><p>{selectedProject.detail}</p><div className="modal-links"><a className="solid-btn" href={selectedProject.github} target="_blank" rel="noreferrer">GitHub 工程代码 <ExternalLink size={15} /></a><a className="outline-btn" href={selectedProject.files[0][1]} download><Download size={15} /> 下载核心代码</a></div></section></div>}
    <footer><span>© 2026 LI WANG</span><span>EMBEDDED · SYSTEMS · CURIOSITY</span><a href="#top">返回顶部 ↑</a></footer>
  </div>;
}
createRoot(document.getElementById('root')).render(<App />);
